use strict;
use XML::DOM;
#use Jcode;
use Image::Size;

use utf8;

my $image_dir;

open FH , "./imgdir.pl";
my @content_all = <FH>;
my $content = join('', 	@content_all);
close FH;

eval $content;

my @keywords;  ;# keywords

my $orgfile;
my $outfile;
my $curpara;
my $curtitle;
my $in_para;
my $a_target;
my $c_count;
my $in_bq = 0;
my $in_comment = 0;

sub unescape_text
{
	my($text);
	$text = $_[0];
	#$text = Jcode->new($text, "utf8")->sjis;
	$text =~ s/---yen---/\\/g;
	$text =~ s/---tilde---/\~/g;
	$text =~ s/---nami---/\x{ff5e}/g;
	$text =~ s/---haifun---/\x{ff0d}/g;
	$text =~ s/&/&amp;/g;
	$text =~ s/</&lt;/g;
	$text =~ s/>/&gt;/g;
	$text =~ s/\t/&nbsp;&nbsp;&nbsp;&nbsp;/g;
	$text =~ s/\"/&quot;/g;
	if($in_bq)
	{
		$text =~ s/ /&nbsp;/g;
		$text =~ s/\/\*/<span class=\"comment\">\/\*/g;
		$text =~ s/\*\//\*\/<\/span>/g;
		if($text =~ s/^(\/\/.*?)$/<span class=\"comment\">$1/s ||
			$text =~ s/([^:])(\/\/.*?)$/$1<span class=\"comment\">$2/s)
		{
			$in_comment = 1;
		}
	}
	return $text;
}

sub quit_comment
{
	if($in_comment)
	{
		$in_comment = 0;
		return "</span>";
	}
	return "";
}

sub html
{
	my($text);
	$text = $_[0];
	$text =~ s/&/&amp;/g;
	$text =~ s/</&lt;/g;
	$text =~ s/>/&gt;/g;
#	$text =~ s/ /&nbsp;/g;
	$text =~ s/\t/&nbsp;&nbsp;&nbsp;&nbsp;/g;
	$text =~ s/\"/&quot;/g;
	return $text;
}

sub text_noquote
{
	my($text);
	$text = $_[0];
	#$text = Jcode->new($text, "utf8")->sjis;
	$text =~ s/---yen---/\\/g;
	$text =~ s/---tilde---/\~/g;
	$text =~ s/---nami---/\x{ff5e}/g;
	$text =~ s/---haifun---/\x{ff0d}/g;
	return $text;
}


sub get_title
{
	my $file = $_[0];
	my $fn;
	$fn = $file . ".xml";
	if(!open(LFH, $fn))
	{
		$fn = $file . ".tag";
		if(!open(LFH, $fn))
		{
			return "";
		}
	}
	binmode(LFH, ":utf8");
	my @all = <LFH>;
	my $all = join('', @all);
	close LFH;
	$all =~ /\<title\>(.*?)\<\/title\>/;
	return $1;
}

sub rr
{
	my($node) = @_;
	my($type);

	$type = $node->getNodeType;
	if($type == ELEMENT_NODE)
	{
		my($name);
		$name = unescape_text($node->getNodeName);
		if($name eq "doc")
		{
			my $title = unescape_text(($node->getElementsByTagName("title"))[0]->getFirstChild->getData);
			$curtitle=$title;

#			my $num = $#keywords  + 1;
#			$keywords[$num] = $title . "\t" . "id$num" . "\t" . $outfile . "\t";

			print OH <<EOF;
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html  xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<!-- generated by to_html.pl from $orgfile -->
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>$title</title>
	<meta name="author" content="W.Dee" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<link href="browser.css" type="text/css" rel="stylesheet" title="Standard style for KiriKiri references" />
	<link href="mailto:dee\@kikyou.info" rev="Made" />
	<link href="index.html" target="_top" rel="Start" title="Top Page" />
</head>
<body>
EOF
#			print OH "<a id=\"id$num\" name=\"id$num\"></a>";


			foreach my $child ($node->getChildNodes) { &rr($child); }

			print OH <<EOF;
	<script type="text/javascript" charset="UTF-8" src="documentid.js" ></script>
	<script type="text/javascript" charset="UTF-8" src="postcontent.js" ></script>
</body>
</html>
EOF

		}
		elsif($name eq "title")
		{
		}
		elsif($name eq "lc")
		{
			$c_count = 0;
		}
		elsif($name eq "l")
		{
			$c_count ++;
			print OH "<span class=\"linenumber\">";
			my $num = sprintf("%3d|", $c_count);
			$num =~ s/ /&nbsp;/g;
			print OH "$num</span>";
		}
		elsif($name eq "para")
		{
			$curpara = '';
			foreach my $child ($node->getChildNodes) { &rr($child); }
			print OH "</div></div>\n";
		}
		elsif($name eq "ptitle")
		{
			my $num = $#keywords  + 1;

			print OH "<h1>";

			print OH "<a id=\"id$num\" name=\"id$num\">";

			$in_para = 1;
			foreach my $child ($node->getChildNodes) { &rr($child); }
			$in_para = 0;

			$keywords[$num] = $curpara . "\t" . "id$num" . "\t" . $outfile . "\t" . $curtitle;


			print OH <<EOF;
</a>
</h1><div class="para"><div>
EOF
		}
		elsif($name eq "note")
		{
			print OH <<EOF;
<br /><div class="note"><div class="notehead"><span class="noteheadspan">Note</span></div>
EOF

			foreach my $child ($node->getChildNodes) { &rr($child); }

			print OH <<EOF;
</div><br />
EOF
		}
		elsif($name eq "descimg")
		{
			my $title = unescape_text(($node->getElementsByTagName("dititle"))[0]->getFirstChild->getData);
			print OH "<br /><div class=\"descimg\">";
			foreach my $child ($node->getChildNodes) { &rr($child); }
			print OH "<br />$title</div><br />";
		}
		elsif($name eq "kw")
		{
			my $word = $node->getFirstChild->getData;
			my $num = $#keywords  + 1;
			$keywords[$num] = text_noquote($word) . "\t" . "id$num" . "\t" . $outfile . "\t";
			if(!$in_para && $curtitle ne $curpara)
			{
				$keywords[$num] .= "$curtitle-$curpara";
			}
			else
			{
				$keywords[$num] .= "$curtitle";
			}
			print OH "<a id=\"id$num\" name=\"id$num\" class=\"targanchor\"><dfn>";
			foreach my $child ($node->getChildNodes) { &rr($child); }
			print OH "</dfn></a>";
		}
		elsif($name eq "img")
		{
			my $filename = $image_dir . $node->getAttribute("src");
			if(-e $filename)
			{
				my $w;
				my $h;
				($w, $h) = imgsize($filename);
				print OH "<img width=\"$w\" height=\"$h\" alt=\"". unescape_text($node->getAttribute("src"))."\" src=\"". unescape_text($node->getAttribute("src"))."\" />";
			}
			else
			{
				print OH "<img src=\"".unescape_text($filename)."\" alt=\"".unescape_text($filename)."\" />";
			}
		}
		elsif($name eq "colorbox")
		{
			my $color=unescape_text($node->getAttribute("color"));
			print OH "<span style=\"border:1px solid black; color:$color; background-color:$color;\">";
			print OH "\x{25a0}";
			print OH "</span>\n";
		}
		elsif($name eq "dt")
		{
			print OH "\n<dt>";
			foreach my $child ($node->getChildNodes) { &rr($child); }
			print OH "</dt>\n";
		}
		elsif($name eq "tt")
		{
			print OH "<code class=\"inlinecode\">";
			foreach my $child ($node->getChildNodes) { &rr($child); }
			print OH "</code>";
		}
		elsif($name eq "b")
		{
			print OH "<em>";
			foreach my $child ($node->getChildNodes) { &rr($child); }
			print OH "</em>";
		}
		elsif($name eq "i")
		{
			print OH "<span class=\"i\">";
			foreach my $child ($node->getChildNodes) { &rr($child); }
			print OH "</span>";
		}
		elsif($name eq "bq")
		{
			print OH "\n<br />